<?php

namespace Database\Seeders;

use App\Models\Rdo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RdoSeeder extends Seeder
{
    public function run()
    {
        $rdo = [
            // RDO
            ['rdo_code' => '001', 'location' => 'Laoag City, Ilocos Norte'],
            ['rdo_code' => '002', 'location' => 'Vigan, Ilocos Sur'],
            ['rdo_code' => '003', 'location' => 'San Fernando, La Union'],
            ['rdo_code' => '004', 'location' => 'Calasiao, West Pangasinan'],
            ['rdo_code' => '005', 'location' => 'Alaminos, Pangasinan'],
            ['rdo_code' => '006', 'location' => 'Urdaneta, Pangasinan'],
            ['rdo_code' => '007', 'location' => 'Bangued, Abra'],
            ['rdo_code' => '008', 'location' => 'Baguio City'],
            ['rdo_code' => '009', 'location' => 'La Trinidad, Benguet'],
            ['rdo_code' => '010', 'location' => 'Bontoc, Mt. Province'],
            ['rdo_code' => '011', 'location' => 'Tabuk City, Kalinga'],
            ['rdo_code' => '012', 'location' => 'Lagawe, Ifugao'],
            ['rdo_code' => '013', 'location' => 'Tuguegarao, Cagayan'],
            ['rdo_code' => '014', 'location' => 'Bayombong, Nueva Vizcaya'],
            ['rdo_code' => '015', 'location' => 'Naguilian, Isabela'],
            ['rdo_code' => '016', 'location' => 'Cabarroguis, Quirino'],
            ['rdo_code' => '017A', 'location' => 'Tarlac City, Tarlac'],
            ['rdo_code' => '017B', 'location' => 'Paniqui, Tarlac'],
            ['rdo_code' => '018', 'location' => 'Olongapo City'],
            ['rdo_code' => '019', 'location' => 'Subic Bay Freeport Zone'],
            ['rdo_code' => '020', 'location' => 'Balanga, Bataan'],
            ['rdo_code' => '21A', 'location' => 'North Pampanga'],
            ['rdo_code' => '21B', 'location' => 'South Pampanga'],
            ['rdo_code' => '21C', 'location' => 'Clark Freeport Zone'],
            ['rdo_code' => '022', 'location' => 'Baler, Aurora'],
            ['rdo_code' => '23A', 'location' => 'North Nueva Ecija'],
            ['rdo_code' => '23B', 'location' => 'South Nueva Ecija'],
            ['rdo_code' => '024', 'location' => 'Valenzuela City'],
            ['rdo_code' => '25A', 'location' => 'Plaridel, Bulacan'],
            ['rdo_code' => '25B', 'location' => 'Sta. Maria, Bulacan'],
            ['rdo_code' => '026', 'location' => 'Malabon-Navotas'],
            ['rdo_code' => '027', 'location' => 'Caloocan City'],
            ['rdo_code' => '028', 'location' => 'Novaliches'],
            ['rdo_code' => '029', 'location' => 'Tondo – San Nicolas'],
            ['rdo_code' => '030', 'location' => 'Binondo'],
            ['rdo_code' => '031', 'location' => 'Sta. Cruz'],
            ['rdo_code' => '032', 'location' => 'Quiapo-Sampaloc-San Miguel-Sta. Mesa'],
            ['rdo_code' => '033', 'location' => 'Intramuros-Ermita-Malate'],
            ['rdo_code' => '034', 'location' => 'Paco-Pandacan-Sta. Ana-San Andres'],
            ['rdo_code' => '035', 'location' => 'Romblon'],
            ['rdo_code' => '036', 'location' => 'Puerto Princesa'],
            ['rdo_code' => '037', 'location' => 'San Jose, Occidental Mindoro'],
            ['rdo_code' => '038', 'location' => 'North Quezon City'],
            ['rdo_code' => '039', 'location' => 'South Quezon City'],
            ['rdo_code' => '040', 'location' => 'Cubao'],
            ['rdo_code' => '041', 'location' => 'Mandaluyong City'],
            ['rdo_code' => '042', 'location' => 'San Juan'],
            ['rdo_code' => '043', 'location' => 'Pasig'],
            ['rdo_code' => '044', 'location' => 'Taguig-Pateros'],
            ['rdo_code' => '045', 'location' => 'Marikina'],
            ['rdo_code' => '046', 'location' => 'Cainta-Taytay'],
            ['rdo_code' => '047', 'location' => 'East Makati'],
            ['rdo_code' => '048', 'location' => 'West Makati'],
            ['rdo_code' => '049', 'location' => 'North Makati'],
            ['rdo_code' => '050', 'location' => 'South Makati'],
            ['rdo_code' => '051', 'location' => 'Pasay City'],
            ['rdo_code' => '052', 'location' => 'Parañaque'],
            ['rdo_code' => '53A', 'location' => 'Las Piñas City'],
            ['rdo_code' => '53B', 'location' => 'Muntinlupa City'],
            ['rdo_code' => '54A', 'location' => 'Trece Martirez City, East Cavite'],
            ['rdo_code' => '54B', 'location' => 'Kawit, West Cavite'],
            ['rdo_code' => '055', 'location' => 'San Pablo City'],
            ['rdo_code' => '056', 'location' => 'Calamba, Laguna'],
            ['rdo_code' => '057', 'location' => 'Biñan, Laguna'],
            ['rdo_code' => '058', 'location' => 'Batangas City'],
            ['rdo_code' => '059', 'location' => 'Lipa City'],
            ['rdo_code' => '060', 'location' => 'Lucena City'],
            ['rdo_code' => '061', 'location' => 'Gumaca, Quezon'],
            ['rdo_code' => '062', 'location' => 'Boac, Marinduque'],
            ['rdo_code' => '063', 'location' => 'Calapan, Oriental Mindoro'],
            ['rdo_code' => '064', 'location' => 'Talisay, Camarines Norte'],
            ['rdo_code' => '065', 'location' => 'Naga City'],
            ['rdo_code' => '066', 'location' => 'Iriga City'],
            ['rdo_code' => '067', 'location' => 'Legazpi City, Albay'],
            ['rdo_code' => '068', 'location' => 'Sorsogon, Sorsogon'],
            ['rdo_code' => '069', 'location' => 'Virac, Catanduanes'],
            ['rdo_code' => '070', 'location' => 'Masbate, Masbate'],
            ['rdo_code' => '071', 'location' => 'Kalibo, Aklan'],
            ['rdo_code' => '072', 'location' => 'Roxas City'],
            ['rdo_code' => '073', 'location' => 'San Jose, Antique'],
            ['rdo_code' => '074', 'location' => 'Iloilo City'],
            ['rdo_code' => '075', 'location' => 'Zarraga, Iloilo City'],
            ['rdo_code' => '076', 'location' => 'Victorias City, Negros Occidental'],
            ['rdo_code' => '077', 'location' => 'Bacolod City'],
            ['rdo_code' => '078', 'location' => 'Binalbagan, Negros Occidental'],
            ['rdo_code' => '079', 'location' => 'Dumaguete City'],
            ['rdo_code' => '080', 'location' => 'Mandaue City'],
            ['rdo_code' => '081', 'location' => 'Cebu City North'],
            ['rdo_code' => '082', 'location' => 'Cebu City South'],
            ['rdo_code' => '083', 'location' => 'Talisay City, Cebu'],
            ['rdo_code' => '084', 'location' => 'Tagbilaran City'],
            ['rdo_code' => '085', 'location' => 'Catarman, Northern Samar'],
            ['rdo_code' => '086', 'location' => 'Borongan, Eastern Samar'],
            ['rdo_code' => '087', 'location' => 'Calbayog City, Samar'],
            ['rdo_code' => '088', 'location' => 'Tacloban City'],
            ['rdo_code' => '089', 'location' => 'Ormoc City'],
            ['rdo_code' => '090', 'location' => 'Maasin, Southern Leyte'],
            ['rdo_code' => '091', 'location' => 'Dipolog City'],
            ['rdo_code' => '092', 'location' => 'Pagadian City, Zamboanga del Sur'],
            ['rdo_code' => '093A', 'location' => 'Zamboanga City, Zamboanga del Sur'],
            ['rdo_code' => '093B', 'location' => 'Ipil, Zamboanga Sibugay'],
            ['rdo_code' => '094', 'location' => 'Isabela, Basilan'],
            ['rdo_code' => '095', 'location' => 'Jolo, Sulu'],
            ['rdo_code' => '096', 'location' => 'Bongao, Tawi-Tawi'],
            ['rdo_code' => '097', 'location' => 'Gingoog City'],
            ['rdo_code' => '098', 'location' => 'Cagayan de Oro City'],
            ['rdo_code' => '099', 'location' => 'Malaybalay City, Bukidnon'],
            ['rdo_code' => '100', 'location' => 'Ozamis City'],
            ['rdo_code' => '101', 'location' => 'Iligan City'],
            ['rdo_code' => '102', 'location' => 'Marawi City'],
            ['rdo_code' => '103', 'location' => 'Butuan City'],
            ['rdo_code' => '104', 'location' => 'Bayugan City, Agusan del Sur'],
            ['rdo_code' => '105', 'location' => 'Surigao City'],
            ['rdo_code' => '106', 'location' => 'Tandag, Surigao del Sur'],
            ['rdo_code' => '107', 'location' => 'Cotabato City'],
            ['rdo_code' => '108', 'location' => 'Kidapawan, North Cotabato'],
            ['rdo_code' => '109', 'location' => 'Tacurong, Sultan Kudarat'],
            ['rdo_code' => '110', 'location' => 'General Santos City'],
            ['rdo_code' => '111', 'location' => 'Koronadal City, South Cotabato'],
            ['rdo_code' => '112', 'location' => 'Tagum, Davao del Norte'],
            ['rdo_code' => '113A', 'location' => 'West Davao City'],
            ['rdo_code' => '113B', 'location' => 'East Davao City'],
            ['rdo_code' => '114', 'location' => 'Mati, Davao Oriental'],
            ['rdo_code' => '115', 'location' => 'Digos, Davao del Sur'],
        ];

        foreach ($rdo as $rdo) {
            Rdo::create($rdo);
        }
    }
}